version: "3.8"

services:
  mongodb:
    container_name: csy-users-service-db
    image: mongo:5.0.19
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DATABASE_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DATABASE_PASSWORD
    ports:
      - ${DATABASE_PORT}:27017
    volumes:
      - db:/data/db
#  app:
#    depends_on:
#      - mongodb
#    build: ./csy-users-service
#    restart: unless-stopped
#    env_file: ./.env
#    ports:
#      - $NODE_LOCAL_PORT:$APP_PORT
#    environment:
#      - DB_HOST=mongodb
#      - DB_USER=$MONGODB_USER
#      - DB_PASSWORD=$MONGODB_PASSWORD
#      - DB_NAME=$MONGODB_DATABASE
#      - DB_PORT=$MONGODB_DOCKER_PORT
#    stdin_open: true
#    tty: true

volumes:
  db: