version: "3.8"

services:
  db:
    container_name: ${DB_NAME}
    image: mongo:5.0.22
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:27017 #todo поменять порт env из докера
    volumes:
      - db:/data/db
  app:
    container_name: ${APP_NAME}
#    working_dir: /${APP_NAME}/
    depends_on:
      - db
    restart: always
    env_file: ./.env
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - DB_URL=db
      - DB_PORT=27017
    build:
      context: ./
      target: ${MODE}
    volumes:
      - ./src:/src
      - ./nodemon.json:/nodemon.json
volumes:
  db:
    name: ${DB_NAME}
