version: "3.8"

services:
  mongodb:
    container_name: ${DB_NAME}
    image: mongo:5.0.22
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:27017
    volumes:
      - db:/data/db
  app:
    container_name: ${APP_NAME}
    depends_on:
      - mongodb
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - DB_URL=mongodb
      - DB_PORT=$MONGODB_PORT
#    stdin_open: true
#    tty: true
#    volumes:
#      - csy-users-service:/csy-users-service

volumes:
  db:
#  csy-users-service:
#  todo пoчинить  volumes app сделать hot reload